apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "{{ .Values.pgadmin.email }}"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "{{ .Values.pgadmin.password }}"
          ports:
            - containerPort: 80
