replicaCount: 1

image:
  repository: amriyass12/service-chat
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8088

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
