apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-service.fullname" . }}
  labels:
    app: {{ include "chat-service.name" . }}
    chart: {{ include "chat-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chat-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "chat-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: regcred   # 👈 Added secret reference
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          resources:   # ✅ prevent resource hogging
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 312Mi
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresdb:5432/chat_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
