server:
  port: 8085

spring:
  application:
    name: service-meet
  cloud:
    compatibility-verifier:
      enabled: false  # Avoid Spring Cloud version compatibility issues
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbituser
    password: rabbitpass
  datasource:
    url: jdbc:postgresql://postgresdb:5432/meetings_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
