apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  username: "postgres"
  password: "123456"
  database: "paiement_db"
  # Bank accounts service credentials
  bank_username: "bankuser"
  bank_password: "bankpassword"
  bank_database: "bank_accounts_db"
