apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-logback
  namespace: default
data:
  logback-spring.xml: |-
    <configuration>
        <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder">
                <customFields>{"appname":"api-gateway-service"}</customFields>
            </encoder>
        </appender>

        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>

        <logger name="org.springframework.web" level="INFO" additivity="false">
            <appender-ref ref="CONSOLE"/>
        </logger>
    </configuration>
