apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ include "rabbitmq.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      name: management
  selector:
    app: {{ include "rabbitmq.name" . }}
