{{- if .Values.realmImport.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-realm
  labels:
    app: {{ include "keycloak.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  realm.json: |
{{ .Values.realmImport.realmData | indent 4 }}
{{- end }}
