replicaCount: 1

image:
  repository: amriyass12/python-notification-service
  tag: "1.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8090
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8090
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5

env:
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASSWORD: "rootpassword"
  DB_NAME: "notification_py_db"
  RABBITMQ_HOST: "rabbitmq.default.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "rabbituser"
  RABBITMQ_PASSWORD: "rabbitpass"
  CHAT_QUEUE: "chat.notification"
  MEET_QUEUE: "meet.notification"
